language: java
jdk:
  - openjdk17

# main 브랜치가 push 될 때 travis ci 수행
branches:
  only:
    - main

# Travis CI 서버의 Home
# cache : 그래이들 의존성을 디렉토리에 캐시해서 다시 받지 않도록 설정
# script : main 브랜치 push 되었을 때 gradlew 통해 clean & build
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - bo8902@gmail.com