name: todays-plot-build-deploy

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # GitHub repository에서 코드를 체크아웃
      - name: Checkout
        uses: actions/checkout@v3

      # JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Gradle을 사용하여 프로젝트 빌드
      - name: Build with Gradle
        run: ./gradlew clean build

      # 빌드 결과를 zip으로 압축
      - name: Zip build files
        run: |
          zip -r todays_plot *
          mkdir -p deploy
          mv todays_plot.zip deploy/todays_plot.zip

      # AWS CLI 설정 (S3와 CodeDeploy에 필요)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # S3에 zip 파일 업로드
      - name: Upload to S3
        run: aws s3 cp deploy/todays_plot.zip s3://todays-plot-build/todays_plot.zip

      # S3 업로드 성공 여부 확인
      - name: Verify S3 upload
        run: aws s3 ls s3://todays-plot-build/ | grep todays_plot.zip
